# Generated by Django 5.1.6 on 2025-02-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
