# Generated by Django 5.1.6 on 2025-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_is_sold_alter_car_category_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
