# Generated by Django 5.1.6 on 2025-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='car_images/default.png', null=True, upload_to='car_images/'),
        ),
    ]
